# using docker container
sudo: false

language: java

jdk:
  - oraclejdk8

before_script:
    - export QINIU_TEST_ENV="travis"

script:
  - ./gradlew  --info clean check
  - tree /home/travis/build/qiniu/java-sdk/build/ -L 2
  - pwd
