language: java

before_script:
    - export QINIU_ACCESS_KEY=ttXNqIvhrYu04B_dWM6GwSpcXOZJvGoYFdznAWnz
    - export QINIU_SECRET_KEY=rX-7Omdag0BIBEtOyuGQXzx4pmTUTeLxoPEw6G8d
    - export QINIU_UP_HOST=http://up.qbox.me
    - export QINIU_RS_HOST=http://rs.qbox.me
    - export QINIU_IO_HOST=http://iovip.qbox.me
    - export QINIU_TEST_BUCKET=junit_bucket
